name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
      
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo snap install uefivars
          sudo apt install --yes efitools
      - uses: actions/checkout@v2
      - name: Run aws-secureboot-blob
        run: |
          ./aws-secureboot-blob -a amd64 -o blob.amd64.bin
          ./aws-secureboot-blob -a arm64 -o blob.arm64.bin
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: blob.*.bin
  aws-test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::156445921216:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: us-east-1
